### ISSUE TITLE
`import files` should handle more file types by default 

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#112]
It would be nice if most standard audio, video, and document extensions were supported. Maybe even all files supported by `get_allowed_mime_types()`?

**Comment by mjangda** [comment]
We could get the list of extensions using something like:

```
wp> str_replace( '|', ',', implode( '|', array_keys( get_allowed_mime_types() ) ) )
```

**Comment by joshbetz** [comment]
Importing all of the default extensions to start sounds good. Maybe we'd want to change the `--types` flag or add another flag to add types to the list rather than overriding it? When there were only a few types in the list, it didn't seem unreasonable to override the full list, but with more the process of adding 1 or 2 custom extensions will be a pain.

**Comment by joshbetz** [comment]
I get:

```jpg,jpeg,jpe,gif,png,bmp,tiff,tif,ico,asf,asx,wmv,wmx,wm,avi,divx,flv,mov,qt,mpeg,mpg,mpe,mp4,m4v,ogv,webm,mkv,3gp,3gpp,3g2,3gp2,txt,asc,c,cc,h,srt,csv,tsv,ics,rtx,css,vtt,dfxp,mp3,m4a,m4b,ra,ram,wav,ogg,oga,mid,midi,wma,wax,mka,rtf,js,pdf,class,tar,zip,gz,gzip,rar,7z,psd,xcf,doc,pot,pps,ppt,wri,xla,xls,xlt,xlw,mdb,mpp,docx,docm,dotx,dotm,xlsx,xlsm,xlsb,xltx,xltm,xlam,pptx,pptm,ppsx,ppsm,potx,potm,ppam,sldx,sldm,onetoc,onetoc2,onetmp,onepkg,oxps,xps,odt,odp,ods,odg,odc,odb,odf,wp,wpd,key,numbers,pages```
