### ISSUE TITLE
Consistency between `app <id>` and `app list`

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#168]
Continued from #163.

Right now, we display different data between `app <id>` and `app list`. It would be nice to consolidate that and show the same (or at least similar) data.

**Comment by elazzabi** [comment]
Currently the `vip app list` command shows the `id`, `name` and `repo`
The `vip app <id>` shows the: `name` of the environment, `repo` (this seems to be a duplication as all branches are part of the same repo, right?), `branch`, `current commit`, `primary domain`

The fields: `current commit` and `primary domain` are for an environment, thus not possible to add them to the `app list` output.
We can add a `branches` field to `app list` to show all branches of an app if we want

Other than that, not sure what we should add/remove/update. Do you have any examples?

**Comment by joshbetz** [comment]
To @elazzabi's point, I think it's somewhat expected that these will be slightly different. Still, doesn't hurt to review this.

> `repo` (this seems to be a duplication as all branches are part of the same repo, right?)

If I remember correctly, we added the repo because it seems important to be able to see the repo when you look up an app. It might be less awkward if we pull it out of the table and only show it once though. Maybe a set of `Key: Value` fields before the table?

**Comment by elazzabi** [comment]
Yeah a `key: value` would be good. And we can add more info to it, something like:
```
id: 11
name: appname
repository: github/something
```
