### ISSUE TITLE
Console error upon login

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-cli#196]
After completing the login flow, an error is logged to the console:

```
 ✕  Unexpected error: Please contact VIP Support with the following error:
  Error: spawn vip-login ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:19)
    at onErrorNT (internal/child_process.js:413:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

The CLI works after that - the token is saved and subsequent commands are authenticated, so it's not the auth process itself, just something with how the process is shutting down.

## Version

This is on v1.1.1 on OSX Mojave.

**Comment by nickdaugherty** [comment]
Oh I think I know why this is.

The CLI smartly prompts for authentication when running any command if you're not currently authenticated, then attempts to run that original command after auth flow completion.

In my case, I ran `vip login`, but it turns out that `login` is not an actual command anywhere, so when it tries to run it later, it fails with the above error.

We should either have a dedicated `vip login` command, or better detect explicit login attempts. Also, we should probably tweak how we call the subcommand after authentication, so we get the same errors, like this, instead of the `ENOENT` one:

```
Error: `something` is not a valid subcommand. See `vip help`
```

**Comment by elazzabi** [comment]
So this is coming from here https://github.com/Automattic/vip/blob/master/src/bin/vip.js#L117

Two solutions:
+ We can specify explicitly that if the subcommand is `login`, do not execute it. The downside is if the user is already logged in, and they execute `vip login` they'll receive an error (the subcommand isn't there)
+ Adding the `login` subcommand: if the user isn't logged in, this will be intercepted in a higher level and will be prompted to login anyway (https://github.com/Automattic/vip/blob/master/src/bin/vip.js#L33). When the command is executed later, we can specify a log saying `You're logged in` in the subcommand as I see we don't confirm the login here https://github.com/Automattic/vip/blob/master/src/bin/vip.js#L115. If the user is already logged in, and they execute `vip login`, they will see the `You're logged in`. the TLDR; a `login` subcommand that only prints `You're logged in` because we're sure if the user isn't logged in, they will be redirected to login before being able to call the subcommand.

And yes, we should tweak how we call the subcommands to offer a good error message.

**Comment by nickdaugherty** [comment]
I think adding `vip login` is the best, especially for the reasons you mention. Plus fixing the error message.

**Comment by nickdaugherty** [comment]
@dchymko ran into this today as well.
