### ISSUE TITLE
False Positive when Validating SQL

### ISSUE THREAD

**Issue by srtfisher** [Automattic/vip-cli#805]
## Expected/Desired Behavior

1. Expected to validate SQL.

## Actual Behavior

Flagged tables in SQL that have an invalid engine though the table has a valid engine.

## Steps to Reproduce the Problem

1. Import a SQL file with some content that includes an engine query string. Here is some example content that matches the current regex: https://regexr.com/6144d

Example string in content that validates SQL things is not InnoDB.

```
http://www.renditionmovie.com/?engine=adwords!10023
```

**Comment by amustaque97** [comment]
Hi @srtfisher, are you facing any issues? 

I'm **not able to reproduce** this issue. I'm using the same data provided in the link. 
Here is the link to my online regex testing https://regex101.com/r/rBYfJl/1

After adding any character at the beginning/ending of data it is actually able to **find the regex**.
![image](https://user-images.githubusercontent.com/21127788/127769361-e6687735-c87e-402c-8564-2aaf1a6dc7ae.png)

**Comment by dchymko** [comment]
It does look like this Regex is incorrectly flagging this case as a problem. In the above RegEx101 example, it shouldn't be flagging that as a match.
A fix could be adding a single space in front of `ENGINE` in the Regex so that it won't flag cases like these.
https://github.com/Automattic/vip/blob/master/src/lib/validations/sql.js#L230

It would be great if we could make this check more robust by something like importing to a temp DB and then checking the table ENGINES for all created tables, but that's a much bigger task.
